apiVersion: v1
kind: Namespace
metadata:
  name: portworx
  labels:
    name: portworx
    app.kubernetes.io/name: portworx
    app.kubernetes.io/part-of: openshift-hypershift-lab
    app.kubernetes.io/managed-by: kustomize
