kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster
  namespace: portworx
  annotations:
    portworx.io/is-openshift: "true"
    portworx.io/misc-args: " -T px-storev2 "
    portworx.io/preflight-check: "true"
    portworx.io/run-on-master: "true" # This is added to run portworx on bare metal master nodes
spec:
  image: portworx/oci-monitor:3.3.1.1
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    deviceSpecs:
    - size=1000
    - size=1000
  secretsProvider: k8s
  startPort: 17001
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
    providers:
    - name: default
      params:
        ## TODO: Populate the cluster routing domain in the overlay
        url: https://thanos-querier-openshift-monitoring.CLUSTER_DOMAIN
      type: prometheus
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      exportMetrics: true
  env:
  - name: PURE_FLASHARRAY_SAN_TYPE
    # For NVMe-of/ROCE
    value: "NVMEOF-RDMA"