apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: portworx-storagecluster

resources:
  - ../../base

labels:
  - pairs:
      environment: default
      deployment-method: gitops
